# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget Common CommonDBus CommonError CommonOpenGL CommonImage CommonLog CommonMath CommonSignal CommonTimer CommonUI CommonUI_GTK CommonXML Common_Test_U)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target Common
add_library(Common STATIC IMPORTED)

set_target_properties(Common PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/Common/src;/mnt/win_d/projects/Common/src/error;/mnt/win_d/projects/Common/src/signal;/mnt/win_d/projects/Common/src/timer;/mnt/win_d/projects/Common/clang/src/.."
)

# Create imported target CommonDBus
add_library(CommonDBus STATIC IMPORTED)

set_target_properties(CommonDBus PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/dbus-1.0;/usr/lib/x86_64-linux-gnu/dbus-1.0/include;/usr/include/systemd;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/Common/src/dbus/..;/mnt/win_d/projects/Common/clang/src/dbus/../.."
)

# Create imported target CommonError
add_library(CommonError STATIC IMPORTED)

set_target_properties(CommonError PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/Common/clang/src/error/../..;/mnt/win_d/projects/Common/src/error/..;/mnt/win_d/projects/Common/src/error/../log"
)

# Create imported target CommonOpenGL
add_library(CommonOpenGL STATIC IMPORTED)

set_target_properties(CommonOpenGL PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/x86_64-linux-gnu//ImageMagick-6;/usr/include/ImageMagick-6;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/Common/src/gl/..;/mnt/win_d/projects/Common/src/gl/../image;/mnt/win_d/projects/Common/clang/src/gl/../.."
)

# Create imported target CommonImage
add_library(CommonImage STATIC IMPORTED)

set_target_properties(CommonImage PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/x86_64-linux-gnu;/usr/include/ImageMagick-6;/usr/include/x86_64-linux-gnu/ImageMagick-6;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/Common/clang/src/image/../..;/mnt/win_d/projects/Common/src/image/..;/mnt/win_d/projects/Common/src/image/../error"
)

# Create imported target CommonLog
add_library(CommonLog STATIC IMPORTED)

set_target_properties(CommonLog PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/Common/src/log/..;/mnt/win_d/projects/Common/clang/src/log/../.."
)

# Create imported target CommonMath
add_library(CommonMath STATIC IMPORTED)

set_target_properties(CommonMath PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/Common/src/math/..;/mnt/win_d/projects/Common/src/math/../timer;/mnt/win_d/projects/Common/clang/src/math/../.."
)

# Create imported target CommonSignal
add_library(CommonSignal STATIC IMPORTED)

set_target_properties(CommonSignal PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/Common/clang/src/signal/../..;/mnt/win_d/projects/Common/src/signal/.."
)

# Create imported target CommonTimer
add_library(CommonTimer STATIC IMPORTED)

set_target_properties(CommonTimer PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/Common/src/timer/..;/mnt/win_d/projects/Common/clang/src/timer/../.."
)

# Create imported target CommonUI
add_library(CommonUI STATIC IMPORTED)

set_target_properties(CommonUI PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/gtk-2.0;/usr/lib/x86_64-linux-gnu/gtk-2.0/include;/usr/include/pango-1.0;/usr/include/atk-1.0;/usr/include/cairo;/usr/include/pixman-1;/usr/include/gdk-pixbuf-2.0;/usr/include/libmount;/usr/include/blkid;/usr/include/pango-1.0;/usr/include/harfbuzz;/usr/include/pango-1.0;/usr/include/fribidi;/usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include;/usr/include/uuid;/usr/include/freetype2;/usr/include/libpng16;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/Common/src/ui/..;/mnt/win_d/projects/Common/src/ui/../error;/mnt/win_d/projects/Common/src/ui/../image;/mnt/win_d/projects/Common/src/ui/../log;/mnt/win_d/projects/Common/src/ui/../xml;/mnt/win_d/projects/Common/clang/src/ui/../.."
)

# Create imported target CommonUI_GTK
add_library(CommonUI_GTK STATIC IMPORTED)

set_target_properties(CommonUI_GTK PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/gtk-2.0;/usr/lib/x86_64-linux-gnu/gtk-2.0/include;/usr/include/pango-1.0;/usr/include/atk-1.0;/usr/include/cairo;/usr/include/pixman-1;/usr/include/gdk-pixbuf-2.0;/usr/include/libmount;/usr/include/blkid;/usr/include/pango-1.0;/usr/include/harfbuzz;/usr/include/pango-1.0;/usr/include/fribidi;/usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include;/usr/include/uuid;/usr/include/freetype2;/usr/include/libpng16;/media/erik/USB_BLACK/lib/gtkglarea;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/Common/clang/src/ui/gtk/../../..;/mnt/win_d/projects/Common/src/ui/gtk/..;/mnt/win_d/projects/Common/src/ui/gtk/../..;/mnt/win_d/projects/Common/src/ui/gtk/../../image;/mnt/win_d/projects/Common/src/ui/gtk/../../log;/mnt/win_d/projects/Common/src/ui/gtk/../../timer"
)

# Create imported target CommonXML
add_library(CommonXML STATIC IMPORTED)

set_target_properties(CommonXML PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/libxml2;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/Common/src/xml/..;/mnt/win_d/projects/Common/clang/src/xml/../.."
)

# Create imported target Common_Test_U
add_library(Common_Test_U STATIC IMPORTED)

set_target_properties(Common_Test_U PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/Common/test_u/../src;/mnt/win_d/projects/Common/clang/test_u/.."
)

# Import target "Common" for configuration "Debug"
set_property(TARGET Common APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Common PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "pthread;rt;cap;CommonDBus;CommonSignal;CommonError"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/Common/clang/src/libCommon.a"
  )

# Import target "CommonDBus" for configuration "Debug"
set_property(TARGET CommonDBus APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CommonDBus PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "systemd"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/Common/clang/src/dbus/libCommonDBus.a"
  )

# Import target "CommonError" for configuration "Debug"
set_property(TARGET CommonError APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CommonError PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/Common/clang/src/error/libCommonError.a"
  )

# Import target "CommonOpenGL" for configuration "Debug"
set_property(TARGET CommonOpenGL APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CommonOpenGL PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "assimp;/usr/lib/x86_64-linux-gnu/libGL.so;/usr/lib/x86_64-linux-gnu/libGLU.so;CommonImage"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/Common/clang/src/gl/libCommonOpenGL.a"
  )

# Import target "CommonImage" for configuration "Debug"
set_property(TARGET CommonImage APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CommonImage PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "avcodec;avformat;swscale;avutil;/usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so;/usr/lib/x86_64-linux-gnu/libMagickWand-6.Q16.so"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/Common/clang/src/image/libCommonImage.a"
  )

# Import target "CommonLog" for configuration "Debug"
set_property(TARGET CommonLog APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CommonLog PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/Common/clang/src/log/libCommonLog.a"
  )

# Import target "CommonMath" for configuration "Debug"
set_property(TARGET CommonMath APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CommonMath PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/Common/clang/src/math/libCommonMath.a"
  )

# Import target "CommonSignal" for configuration "Debug"
set_property(TARGET CommonSignal APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CommonSignal PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/Common/clang/src/signal/libCommonSignal.a"
  )

# Import target "CommonTimer" for configuration "Debug"
set_property(TARGET CommonTimer APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CommonTimer PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/Common/clang/src/timer/libCommonTimer.a"
  )

# Import target "CommonUI" for configuration "Debug"
set_property(TARGET CommonUI APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CommonUI PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "X11;Xrandr"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/Common/clang/src/ui/libCommonUI.a"
  )

# Import target "CommonUI_GTK" for configuration "Debug"
set_property(TARGET CommonUI_GTK APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CommonUI_GTK PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "gmodule-2.0;gthread-2.0;gtk-x11-2.0;gdk-x11-2.0;pangocairo-1.0;atk-1.0;cairo;gdk_pixbuf-2.0;gio-2.0;pangoft2-1.0;pango-1.0;gobject-2.0;glib-2.0;fontconfig;freetype;/media/erik/USB_BLACK/lib/gtkglarea/gtkgl/.libs/libgtkgl-2.0.a;X11;GL"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/Common/clang/src/ui/gtk/libCommonUI_GTK.a"
  )

# Import target "CommonXML" for configuration "Debug"
set_property(TARGET CommonXML APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CommonXML PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "/media/erik/USB_BLACK/lib/ACE_TAO/ACE/lib/libACEXML.so;/media/erik/USB_BLACK/lib/ACE_TAO/ACE/lib/libACEXML_Parser.so"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/Common/clang/src/xml/libCommonXML.a"
  )

# Import target "Common_Test_U" for configuration "Debug"
set_property(TARGET Common_Test_U APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Common_Test_U PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/Common/clang/test_u/libCommon_Test_U.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
