if (UNIX)
elseif (WIN32)
# set (MSXML_FOUND ON)
 set (MSXML_SUPPORT ON)
 add_definitions (-DMSXML_SUPPORT)
 # *TODO*: repair pkgconfig support on this platform
 set (LIBXML_INCLUDE_DIRS "$ENV{LIB_ROOT}/libxml2/include")
 set (LIBXML_LIBRARY_DIRS "$ENV{LIB_ROOT}/libxml2/lib")
# message (STATUS "PC_LIBXML_INCLUDEDIR: ${PC_LIBXML_INCLUDEDIR}")
endif ()
find_package (LibXml2 MODULE)
if (LIBXML2_FOUND)
 set (LIBXML2_SUPPORT ON)
 add_definitions (-DLIBXML2_SUPPORT)
endif (LIBXML2_FOUND)
