include (ACEXML)

if (UNIX)
elseif (WIN32)
# set (MSXML_FOUND ON)
 set (MSXML_SUPPORT ON)
 add_definitions (-DMSXML_SUPPORT)
 # *TODO*: repair pkgconfig support on this platform
 set (PC_LIBXML_INCLUDEDIR "$ENV{LIB_ROOT}/libxml2/include")
 set (PC_LIBXML_LIBDIR "$ENV{LIB_ROOT}/libxml2/lib")
# message (STATUS "PC_LIBXML_INCLUDEDIR: ${PC_LIBXML_INCLUDEDIR}")
endif ()
find_package (LibXml2 MODULE)
if (LIBXML2_FOUND)
 set (LIBXML2_SUPPORT ON)
 add_definitions (-DLIBXML2_SUPPORT)
endif (LIBXML2_FOUND)
if (EXISTS ${ACEXML_LIBRARY})
 set (ACEXML_SUPPORT ON)
 add_definitions (-DACEXML_SUPPORT)
endif (ACEXML_FOUND)
