name: 'install_deps'
description: 'install package dependencies on the runner'
inputs:
 os:  # id of input
  description: 'runner OS'
  required: true
runs:
 using: "composite"
 steps:
  - run: sudo apt-get update
    shell: bash
  - run: sudo apt-get install -y libaio-dev libcap-dev libdbus-1-dev libsystemd-dev libmagick++-dev libmagickwand-6.q16-dev libglu1-mesa-dev libglm-dev libassimp-dev libavcodec-dev libswscale-dev libgtk2.0-dev
    shell: bash
#    if: inputs.os == 'ubuntu-latest'
#  - run:
#    shell: bash
#    if: inputs.os == 'windows-latest'
#  - run:
#   shell: bash
#   if: inputs.os == 'macos-latest'
