if (UNIX)
 include (FindPkgConfig)
 pkg_check_modules (PKG_ASSIMP assimp)
 if (PKG_ASSIMP_FOUND)
  set (ASSIMP_FOUND TRUE)
  set (ASSIMP_INCLUDE_DIRS ${PKG_ASSIMP_INCLUDE_DIRS})
  if (CMAKE_SYSTEM_NAME MATCHES "Linux")
   include (OS)
#   message (STATUS "on Linux")
   if (${LSB_RELEASE_ID_SHORT} MATCHES "Ubuntu")
#    message (STATUS "on Ubuntu")
# *WORKAROUND*: there seems to be a problem on Ubuntu
    set (ASSIMP_INCLUDE_DIRS "/usr/include/assimp")
   endif (${LSB_RELEASE_ID_SHORT} MATCHES "Ubuntu")
  endif (CMAKE_SYSTEM_NAME MATCHES "Linux")
  set (ASSIMP_LIBRARIES ${PKG_ASSIMP_LIBRARIES})
 endif (PKG_ASSIMP_FOUND)
# find_library (ASSIMP_LIBRARY libassimp.so.3
#               DOC "searching for libassimp")
# if (NOT ASSIMP_LIBRARY)
#  message (FATAL_ERROR "could not find libassimp, aborting")
# endif (NOT ASSIMP_LIBRARY)
elseif (WIN32)
 if (VCPKG_SUPPORT)
#  cmake_policy (SET CMP0074 OLD)
  find_package (assimp CONFIG)
  if (assimp_FOUND)
   message (STATUS "found assimp")
   set (ASSIMP_FOUND TRUE)
   set (ASSIMP_INCLUDE_DIRS "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
  endif (assimp_FOUND)
 endif (VCPKG_SUPPORT)
 if (NOT ASSIMP_FOUND)
  set (ASSIMP_FOUND TRUE)
  set (ASSIMP_INCLUDE_DIRS "$ENV{LIB_ROOT}/assimp/include;$ENV{LIB_ROOT}/assimp/cmake/include")
  set (ASSIMP_LIBRARIES "$ENV{LIB_ROOT}/assimp/cmake/code/${CMAKE_BUILD_TYPE}/assimp-vc140-mt.lib")
  set (ASSIMP_LIB_DIR "$ENV{LIB_ROOT}/assimp/cmake/code/${CMAKE_BUILD_TYPE}")
 endif (NOT ASSIMP_FOUND)
endif ()
if (ASSIMP_FOUND)
 option (ASSIMP_SUPPORT "enable assimp support" ON)
 if (ASSIMP_SUPPORT)
  add_definitions (-DASSIMP_SUPPORT)
 endif (ASSIMP_SUPPORT)
endif (ASSIMP_FOUND)
