if (UNIX)
# include (FindPkgConfig)
# pkg_check_modules (PKG_LIBPNG libpng)
 find_library (PNG_LIBRARY libpng16.so.16
               DOC "searching for libpng")
 if (NOT PNG_LIBRARY)
  message (WARNING "could not find libpng, continuing")
 else ()
  message (STATUS "Found libpng \"${PNG_LIBRARY}\"")
  set (PNG_FOUND TRUE)
  set (PNG_LIBRARIES "${PNG_LIBRARY}")
 endif (NOT PNG_LIBRARY)
elseif (WIN32)
 if (VCPKG_SUPPORT)
#  cmake_policy (SET CMP0074 OLD)
  find_package (libpng CONFIG)
  if (libpng_FOUND)
   message (STATUS "found libpng")
   set (PNG_FOUND TRUE)
   set (PNG_INCLUDE_DIRS "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
   if (CMAKE_BUILD_TYPE STREQUAL "Debug" OR
       CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    set (PNG_LIB_DIR "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug/bin")
   else ()
    set (PNG_LIB_DIR "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/bin")
   endif ()
  endif (libpng_FOUND)
 endif (VCPKG_SUPPORT)
 if (NOT PNG_FOUND)
  message (STATUS "found libpng")
  set (PNG_FOUND TRUE)
  set (PNG_INCLUDE_DIRS "$ENV{LIB_ROOT}/libpng/cmake;$ENV{LIB_ROOT}/libpng")
  set (PNG_LIBRARIES "$ENV{LIB_ROOT}/libpng/cmake/${CMAKE_BUILD_TYPE}/libpng16${LIB_FILE_SUFFIX}.lib")
  set (PNG_LIB_DIR "$ENV{LIB_ROOT}/libpng/cmake/${CMAKE_BUILD_TYPE}")
 endif (NOT PNG_FOUND)
endif ()
if (PNG_FOUND)
 option (LIBPNG_SUPPORT "enable libpng support" ON)
 if (LIBPNG_SUPPORT)
  add_definitions (-DLIBPNG_SUPPORT)
 endif (LIBPNG_SUPPORT)
endif (PNG_FOUND)
