set (BOX2D_SUPPORT_DEFAULT ON)
if (UNIX)
# set (ENV{PKG_CONFIG_PATH} "/usr/local/lib/pkgconfig:$ENV{PKG_CONFIG_PATH}")
 pkg_check_modules (PKG_BOX2D box2d)
 if (PKG_BOX2D_FOUND)
  set (BOX2D_FOUND TRUE)
  set (BOX2D_INCLUDE_DIRS "${PKG_BOX2D_INCLUDE_DIRS}")
  set (BOX2D_LIBRARIES "${PKG_BOX2D_LIBRARIES}")
 else ()
  find_library (BOX2D_LIBRARY libbox2d.a
                PATHS $ENV{LIB_ROOT}/box2d/build/gcc
                PATH_SUFFIXES ${CMAKE_BUILD_TYPE}
                DOC "searching for box2d"
                NO_DEFAULT_PATH)
  if (NOT BOX2D_LIBRARY)
   message (WARNING "could not find libbox2d.a, continuing")
  endif (NOT BOX2D_LIBRARY)
  if (BOX2D_LIBRARY)
   message (STATUS "found Box2D")
   set (BOX2D_FOUND TRUE)
   set (BOX2D_INCLUDE_DIRS "$ENV{LIB_ROOT}/box2d/include")
   set (BOX2D_LIBRARIES ${BOX2D_LIBRARY})
#  set (BOX2D_LIB_DIR "$ENV{LIB_ROOT}/box2d/build/gcc/${CMAKE_BUILD_TYPE}")
  endif (BOX2D_LIBRARY)
 endif (PKG_BOX2D_FOUND)
elseif (WIN32)
 if (VCPKG_USE)
#  cmake_policy (SET CMP0074 OLD)
  find_package (box2d CONFIG)
  if (BOX2D_FOUND)
   set (BOX2D_FOUND TRUE)
   set (BOX2D_INCLUDE_DIRS "${VCPKG_INCLUDE_DIR}")
   set (BOX2D_LIBRARIES "${VCPKG_LIB_DIR}/box2d${LIB_FILE_SUFFIX}.lib")
   set (BOX2D_LIB_DIR "${VCPKG_BIN_DIR}")
  endif (BOX2D_FOUND)
 endif (VCPKG_USE)
 if (NOT BOX2D_FOUND)
  if (EXISTS $ENV{BOX2D_ROOT})
   set (BOX2D_ROOT $ENV{BOX2D_ROOT})
  else ()
   set (BOX2D_ROOT $ENV{LIB_ROOT}/box2d)
  endif (EXISTS $ENV{BOX2D_ROOT})
  file (TO_CMAKE_PATH "${BOX2D_ROOT}" BOX2D_ROOT)
  find_library (BOX2D_LIBRARY "box2d${LIB_FILE_SUFFIX}.lib"
                PATHS ${BOX2D_ROOT}/build/msvc/src
                PATH_SUFFIXES ${CMAKE_BUILD_TYPE}
                DOC "searching for box2d.lib"
                NO_DEFAULT_PATH)
  if (NOT BOX2D_LIBRARY)
   message (WARNING "could not find box2d.lib, continuing")
  endif (NOT BOX2D_LIBRARY)
  if (BOX2D_LIBRARY)
   message (STATUS "found Box2D")
   set (BOX2D_FOUND TRUE)
   set (BOX2D_INCLUDE_DIRS "${BOX2D_ROOT}/include")
   set (BOX2D_LIBRARIES ${BOX2D_LIBRARY})
   set (BOX2D_LIB_DIR "${BOX2D_ROOT}/build/msvc/src/${CMAKE_BUILD_TYPE}")
  endif (BOX2D_LIBRARY)
 endif (NOT BOX2D_FOUND)
endif ()
if (BOX2D_FOUND)
 option (BOX2D_SUPPORT "enable box2d support" ${BOX2D_SUPPORT_DEFAULT})
 if (BOX2D_SUPPORT)
  add_definitions (-DBOX2D_SUPPORT)
 endif (BOX2D_SUPPORT)
endif (BOX2D_FOUND)
