set (FFTW_SUPPORT_DEFAULT ON)
if (UNIX)
 find_package (fftw MODULE)
 if (FFTW_FOUND)
  message (STATUS "found fftw")
  set (FFTW_FOUND TRUE)
 else ()
  pkg_check_modules (PKG_FFTW fftw3f)
  if (PKG_FFTW_FOUND)
   message (STATUS "found fftw")
   set (FFTW_FOUND TRUE)
   set (FFTW_INCLUDE_DIRS "${PKG_FFTW_INCLUDE_DIRS}")
   set (FFTW_LIBRARIES ${PKG_FFTW_LIBRARIES})
  endif (PKG_FFTW_FOUND)
 endif (FFTW_FOUND)
elseif (WIN32)
 if (VCPKG_USE)
  find_package (FFTW)
  if (FFTW_FOUND)
   message (STATUS "found fftw")
   set (FFTW_FOUND TRUE)
   set (FFTW_INCLUDE_DIR "${VCPKG_INCLUDE_DIR}/fftw")
   set (FFTW_LIBRARIES "${VCPKG_LIB_DIR}/fftw.lib")
   set (FFTW_LIB_DIR "${VCPKG_BIN_DIR}")
  endif (FFTW_FOUND)
 endif (VCPKG_USE)
 if (NOT FFTW_FOUND)
  find_library (FFTW_LIBRARY
                NAMES libfftw3f-3.lib
                PATHS "$ENV{LIB_ROOT}"
                PATH_SUFFIXES fftw
                NO_DEFAULT_PATH)
  if (FFTW_LIBRARY)
   message (STATUS "found fftw")
   set (FFTW_FOUND TRUE)
   set (FFTW_INCLUDE_DIRS "$ENV{LIB_ROOT}/fftw")
   set (FFTW_LIBRARIES ${FFTW_LIBRARY})
   set (FFTW_LIB_DIR "$ENV{LIB_ROOT}/fftw")
  else ()
   message (WARNING "could not find fftw, continuing")
  endif (FFTW_LIBRARY)
 endif (NOT FFTW_FOUND)
endif ()
if (FFTW_FOUND)
 option (FFTW_SUPPORT "enable fftw support" ${FFTW_SUPPORT_DEFAULT})
 if (FFTW_SUPPORT)
  add_definitions (-DFFTW_SUPPORT)
 endif (FFTW_SUPPORT)
endif (FFTW_FOUND)
