set (LIQUIDFUN_SUPPORT_DEFAULT ON)
if (UNIX)
# set (ENV{PKG_CONFIG_PATH} "/usr/local/lib/pkgconfig:$ENV{PKG_CONFIG_PATH}")
 pkg_check_modules (PKG_LIQUIDFUN liquidfun)
 if (PKG_LIQUIDFUN_FOUND)
  set (LIQUIDFUN_FOUND TRUE)
  set (LIQUIDFUN_INCLUDE_DIRS "${PKG_LIQUIDFUN_INCLUDE_DIRS}")
  set (LIQUIDFUN_LIBRARIES "${PKG_LIQUIDFUN_LIBRARIES}")
 else ()
  find_library (LIQUIDFUN_LIBRARY libliquidfun.a
                PATHS $ENV{LIB_ROOT}/liquidfun/build/gcc/Box2D
                PATH_SUFFIXES ${CMAKE_BUILD_TYPE}
                DOC "searching for libliquidfun.a"
                NO_DEFAULT_PATH)
  if (NOT LIQUIDFUN_LIBRARY)
   message (WARNING "could not find libliquidfun.a, continuing")
  endif (NOT LIQUIDFUN_LIBRARY)
  if (LIQUIDFUN_LIBRARY)
   message (STATUS "found liquidfun")
   set (LIQUIDFUN_FOUND TRUE)
   set (LIQUIDFUN_INCLUDE_DIRS "$ENV{LIB_ROOT}/liquidfun/liquidfun/Box2D")
   set (LIQUIDFUN_LIBRARIES ${LIQUIDFUN_LIBRARY})
  endif (LIQUIDFUN_LIBRARY)
 endif (PKG_LIQUIDFUN_FOUND)
elseif (WIN32)
 if (VCPKG_USE)
#  cmake_policy (SET CMP0074 OLD)
  find_package (LIQUIDFUN CONFIG)
  if (LIQUIDFUN_FOUND)
   set (LIQUIDFUN_FOUND TRUE)
   set (LIQUIDFUN_INCLUDE_DIRS "${VCPKG_INCLUDE_DIR}")
   set (LIQUIDFUN_LIBRARIES "${VCPKG_LIB_DIR}/liquidfun.lib")
   set (LIQUIDFUN_LIB_DIR "${VCPKG_BIN_DIR}")
  endif (LIQUIDFUN_FOUND)
 endif (VCPKG_USE)
 if (NOT LIQUIDFUN_FOUND)
  if (EXISTS $ENV{LIQUIDFUN_ROOT})
   set (LIQUIDFUN_ROOT $ENV{LIQUIDFUN_ROOT})
  else ()
   set (LIQUIDFUN_ROOT $ENV{LIB_ROOT}/liquidfun)
  endif (EXISTS $ENV{LIQUIDFUN_ROOT})
  file (TO_CMAKE_PATH "${LIQUIDFUN_ROOT}" LIQUIDFUN_ROOT)
  find_library (LIQUIDFUN_LIBRARY liquidfun.lib
                PATHS ${LIQUIDFUN_ROOT}/build/msvc/Box2D
                PATH_SUFFIXES ${CMAKE_BUILD_TYPE}
                DOC "searching for liquidfun.lib"
                NO_DEFAULT_PATH)
  if (NOT LIQUIDFUN_LIBRARY)
   message (WARNING "could not find liquidfun.lib, continuing")
  endif (NOT LIQUIDFUN_LIBRARY)
  if (LIQUIDFUN_LIBRARY)
   message (STATUS "found liquidfun")
   set (LIQUIDFUN_FOUND TRUE)
   set (LIQUIDFUN_INCLUDE_DIRS "${LIQUIDFUN_ROOT}/liquidfun/Box2D")
   set (LIQUIDFUN_LIBRARIES ${LIQUIDFUN_LIBRARY})
#   set (LIQUIDFUN_LIB_DIR "${LIQUIDFUN_ROOT}/liquidfun/build/msvc/Box2D/${CMAKE_BUILD_TYPE}")
  endif (LIQUIDFUN_LIBRARY)
 endif (NOT LIQUIDFUN_FOUND)
endif ()
if (LIQUIDFUN_FOUND)
 option (LIQUIDFUN_SUPPORT "enable liquidfun support" ${LIQUIDFUN_SUPPORT_DEFAULT})
 if (LIQUIDFUN_SUPPORT)
  add_definitions (-DLIQUIDFUN_SUPPORT)
 endif (LIQUIDFUN_SUPPORT)
endif (LIQUIDFUN_FOUND)
