set (ROCM_SUPPORT_DEFAULT ON)
if (UNIX)
 find_package (rocblas MODULE)
 if (ROCM_FOUND)
  message (STATUS "found rocm")
  set (ROCM_FOUND TRUE)
 else ()
  pkg_check_modules (PKG_ROCM_BLAS rocblas)
  if (PKG_ROCM_BLAS_FOUND)
   message (STATUS "found rocm")
   set (ROCM_FOUND TRUE)
   set (ROCM_INCLUDE_DIRS "${PKG_ROCM_BLAS_INCLUDE_DIRS}")
   set (ROCM_LIBRARIES ${PKG_ROCM_BLAS_LIBRARIES})
  endif (PKG_ROCM_BLAS_FOUND)
 endif (ROCM_FOUND)
elseif (WIN32)
 if (VCPKG_USE)
  find_package (rocblas)
  if (ROCM_FOUND)
   message (STATUS "found rocm")
   set (ROCM_FOUND TRUE)
   set (ROCM_INCLUDE_DIR "${VCPKG_INCLUDE_DIR}/rocm")
   set (ROCM_LIBRARIES "${VCPKG_LIB_DIR}/rocblas.lib")
   set (ROCM_LIB_DIR "${VCPKG_BIN_DIR}")
  endif (ROCM_FOUND)
 endif (VCPKG_USE)
 if (NOT ROCM_FOUND)
  find_library (ROCM_BLAS_LIBRARY
                NAMES rocblas.lib
                PATHS "$ENV{ROCM_PATH}"
                PATH_SUFFIXES lib
                NO_DEFAULT_PATH)
  if (ROCM_LIBRARY)
   message (STATUS "found rocm")
   set (ROCM_FOUND TRUE)
   set (ROCM_INCLUDE_DIRS "$ENV{ROCM_PATH}/include")
   set (ROCM_LIBRARIES ${ROCM_BLAS_LIBRARY})
   set (ROCM_LIB_DIR "$ENV{ROCM_PATH}/bin")
  else ()
   message (WARNING "could not find rocm, continuing")
  endif (ROCM_LIBRARY)
 endif (NOT ROCM_FOUND)
endif ()
if (ROCM_FOUND)
 option (ROCM_SUPPORT "enable rocm support" ${ROCM_SUPPORT_DEFAULT})
 if (ROCM_SUPPORT)
  add_definitions (-DROCM_SUPPORT)
 endif (ROCM_SUPPORT)
endif (ROCM_FOUND)
