if (UNIX)
# find_package (DBus1 MODULE)
 find_package (DBus1)
 if (NOT DBus1_FOUND)
  include (FindPkgConfig)
  pkg_check_modules (PKG_DBUS dbus-1)
  if (NOT PKG_DBUS_FOUND)
   find_library (DBUS_LIBRARY libdbus-1.so
                 PATHS /usr/lib64
                 DOC "searching for libdbus-1")
   if (NOT DBUS_LIBRARY)
    message (WARNING "could not find libdbus-1, continuing")
   else ()
    set (DBUS1_FOUND TRUE)
   endif (NOT DBUS_LIBRARY)
  else ()
   set (DBUS1_FOUND TRUE)
  endif (NOT PKG_DBUS_FOUND)
 else ()
  set (DBUS1_FOUND TRUE)
  if (CMAKE_SYSTEM_NAME MATCHES "Linux")
   include (OS)
   if (${LSB_RELEASE_ID_SHORT} MATCHES "Fedora")
# message (STATUS "DBus1_INCLUDE_DIRS: ${DBus1_INCLUDE_DIRS}")
#*NOTE*: add a missing directory (Fedora 34)
    set (PKG_DBUS_INCLUDE_DIRS "${DBus1_INCLUDE_DIRS};/usr/lib64/dbus-1.0/include")
   endif (${LSB_RELEASE_ID_SHORT} MATCHES "Fedora")
  endif (CMAKE_SYSTEM_NAME MATCHES "Linux")
 endif (NOT DBus1_FOUND)
 if (DBUS1_FOUND)
  message (STATUS "found DBus1")
  option (DBUS_SUPPORT "enable dbus support" ON)
  if (DBUS_SUPPORT)
   add_definitions (-DDBUS_SUPPORT)
  endif (DBUS_SUPPORT)
 endif (DBUS1_FOUND)
endif (UNIX)
