// -*- C++ -*-
//
// generated by wxGlade 0.8.3 on Wed Mar 20 14:52:09 2019
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include "test_u_3_ui_base.h"

// begin wxGlade: ::extracode
// end wxGlade



dialog_main_base::dialog_main_base(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
  wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
//  // begin wxGlade: dialog_main_base::dialog_main_base
//  button_1 = new wxButton(this, wxID_NEW, wxEmptyString);
//  button_2 = new wxButton(this, wxID_COPY, wxEmptyString);
//  button_3 = new wxButton(this, wxID_CLEAR, wxEmptyString);

//  set_properties();
//  do_layout();
//  // end wxGlade
}


void dialog_main_base::set_properties()
{
  // begin wxGlade: dialog_main_base::set_properties
  SetTitle(wxT("dialog"));
  button_1->SetFocus();
  button_1->SetDefault();
  button_3->Enable(0);
  // end wxGlade
}


void dialog_main_base::do_layout()
{
  // begin wxGlade: dialog_main_base::do_layout
  wxBoxSizer* sizer_v_main = new wxBoxSizer(wxVERTICAL);
  sizer_v_main->Add(button_1, 0, 0, 0);
  sizer_v_main->Add(button_2, 0, 0, 0);
  sizer_v_main->Add(button_3, 0, 0, 0);
  SetSizer(sizer_v_main);
  sizer_v_main->Fit(this);
  Layout();
  // end wxGlade
}


//BEGIN_EVENT_TABLE(dialog_main_base, wxDialog)
//  // begin wxGlade: dialog_main_base::event_table
//  EVT_BUTTON(wxID_ANY, dialog_main_base::button_1_clicked_cb)
//  EVT_BUTTON(wxID_ANY, dialog_main_base::button_2_clicked_cb)
//  EVT_BUTTON(wxID_ANY, dialog_main_base::button_3_clicked_cb)
//  // end wxGlade
//END_EVENT_TABLE();


void dialog_main_base::button_1_clicked_cb(wxCommandEvent &event)  // wxGlade: dialog_main_base.<event_handler>
{
  event.Skip();
  // notify the user that he hasn't implemented the event handler yet
  wxLogDebug(wxT("Event handler (dialog_main_base::button_1_clicked_cb) not implemented yet"));
}

void dialog_main_base::button_2_clicked_cb(wxCommandEvent &event)  // wxGlade: dialog_main_base.<event_handler>
{
  event.Skip();
  // notify the user that he hasn't implemented the event handler yet
  wxLogDebug(wxT("Event handler (dialog_main_base::button_2_clicked_cb) not implemented yet"));
}

void dialog_main_base::button_3_clicked_cb(wxCommandEvent &event)  // wxGlade: dialog_main_base.<event_handler>
{
  event.Skip();
  // notify the user that he hasn't implemented the event handler yet
  wxLogDebug(wxT("Event handler (dialog_main_base::button_3_clicked_cb) not implemented yet"));
}


// wxGlade: add dialog_main_base event handlers


//class Test_U_wxWidgets_Application: public wxApp {
//public:
//  bool OnInit();
//};

//IMPLEMENT_APP(Test_U_wxWidgets_Application)

//bool Test_U_wxWidgets_Application::OnInit()
//{
//  wxInitAllImageHandlers();
//  dialog_main_base* dialog_main_base = new dialog_main_base(NULL, wxID_ANY, wxEmptyString);
//  SetTopWindow(dialog_main_base);
//  dialog_main_base->Show();
//  return true;
//}
