name: 'install_deps_win32'
description: 'install package dependencies on the runner'
inputs:
 os:  # id of input
  description: 'runner OS'
  required: true
runs:
 using: "composite"
 steps:
  - uses: lukka/run-vcpkg@v7.4
    with:
     setupOnly: true
     vcpkgGitCommitId: 'a79d4a8ec7ae4464eb22f6af23e277882a67595d'
  - run: vcpkg install assimp directxsdk ffmpeg freeglut glm graphicsmagick gtk
    shell: cmd
#    if: inputs.os == 'ubuntu-latest'
#  - run:
#    shell: bash
#    if: inputs.os == 'windows-latest'
#  - run:
#   shell: bash
#   if: inputs.os == 'macos-latest'
