name: 'install_deps_win32'
description: 'install package dependencies on the runner'
inputs:
 os:  # id of input
  description: 'runner OS'
  required: true
runs:
 using: "composite"
 steps:
  - uses: lukka/run-vcpkg@v10
    with:
     setupOnly: true
     vcpkgGitCommitId: '30a20e8f15ff26eec665205dea52f4ffc6f0814b'
  - run: |
         vcpkg update
         vcpkg install assimp directxsdk ffmpeg freeglut glm graphicsmagick gtk
    shell: cmd
