if (GTK_SUPPORT)
 # *NOTE*: the first entry is the default option
 set (GTK_VERSION "gtk 3" CACHE STRING "use GTK 3 (default)")
 set (GTK_VERSION "gtk 2" CACHE STRING "use GTK 2")

 set_property (CACHE GTK_VERSION PROPERTY STRINGS "gtk3" "gtk2")

 if (NOT (DEFINED GTK_VERSION_LAST))
  set (GTK_VERSION_LAST "NotAVersion" CACHE STRING "last GTK version used")
  mark_as_advanced (FORCE GTK_VERSION_LAST)
 endif ()
 if (NOT (${GTK_VERSION} MATCHES ${GTK_VERSION_LAST}))
  unset (GTK3_USE CACHE)
  unset (GTK2_USE CACHE)
  set (GTK_VERSION_LAST ${GTK_VERSION} CACHE STRING "Updating GTK Version Option" FORCE)
 endif ()

 if (${GTK_VERSION} MATCHES "gtk3")
  if (NOT GTK3_SUPPORT)
   message (FATAL_ERROR "GTK3 not supported")
  endif ()
  set (GTK3_USE ON CACHE STRING "use GTK3")
  mark_as_advanced (FORCE GTK3_USE)
  add_definitions (-DGTK3_USE)
 elseif (${GTK_VERSION} MATCHES "gtk2")
  if (NOT GTK2_SUPPORT)
   message (FATAL_ERROR "GTK2 not supported")
  endif ()
  set (GTK2_USE ON CACHE STRING "use GTK2")
  mark_as_advanced (FORCE GTK2_USE)
  add_definitions (-DGTK2_USE)
 endif ()
endif (GTK_SUPPORT)

