if (GTK_SUPPORT AND GTK_USE)
 # *NOTE*: the first entry is the default option
 if (UNIX)
  set (GTK_VERSION "gtk3" CACHE STRING "use GTK3 (default)")
  set (GTK_VERSION "gtk2" CACHE STRING "use GTK2")
  set_property (CACHE GTK_VERSION PROPERTY STRINGS "gtk3" "gtk2")
 elseif (WIN32)
  set (GTK_VERSION "gtk2" CACHE STRING "use GTK2 (default)")
  set (GTK_VERSION "gtk3" CACHE STRING "use GTK3")
  set_property (CACHE GTK_VERSION PROPERTY STRINGS "gtk2" "gtk3")
 endif ()

 if (NOT (DEFINED GTK_VERSION_LAST))
  set (GTK_VERSION_LAST "NotAVersion" CACHE STRING "last GTK version used")
  mark_as_advanced (FORCE GTK_VERSION_LAST)
 endif ()
 if (NOT (${GTK_VERSION} MATCHES ${GTK_VERSION_LAST}))
  unset (GTK2_USE CACHE)
  unset (GTK3_USE CACHE)
  set (GTK_VERSION_LAST ${GTK_VERSION} CACHE STRING "Updating GTK Version Option" FORCE)
 endif ()

 if (${GTK_VERSION} MATCHES "gtk2")
  if (NOT GTK2_SUPPORT)
   if (GTK3_SUPPORT)
    message (WARNING "GTK2 not supported, falling back")
    set (GTK3_USE ON CACHE STRING "use GTK3")
    mark_as_advanced (FORCE GTK3_USE)
    add_definitions (-DGTK3_USE)
   else ()
    message (FATAL_ERROR "GTK2 not supported, aborting")  
   endif (GTK3_SUPPORT)
  else ()
   set (GTK2_USE ON CACHE STRING "use GTK2")
   mark_as_advanced (FORCE GTK2_USE)
   add_definitions (-DGTK2_USE)

   set (GTK_INCLUDE_DIRS ${GTK2_INCLUDE_DIRS})
   set (GTK_LIBRARIES ${GTK2_LIBRARIES})
  endif (NOT GTK2_SUPPORT)
 elseif (${GTK_VERSION} MATCHES "gtk3")
  if (NOT GTK3_SUPPORT)
   if (GTK2_SUPPORT)
    message (WARNING "GTK3 not supported, falling back")
    set (GTK2_USE ON CACHE STRING "use GTK2")
    mark_as_advanced (FORCE GTK2_USE)
    add_definitions (-DGTK2_USE)
   else ()
    message (FATAL_ERROR "GTK3 not supported, aborting")  
   endif (GTK2_SUPPORT)
  else ()
   set (GTK3_USE ON CACHE STRING "use GTK3")
   mark_as_advanced (FORCE GTK3_USE)
   add_definitions (-DGTK3_USE)

   set (GTK_INCLUDE_DIRS ${GTK3_INCLUDE_DIRS})
   set (GTK_LIBRARIES ${GTK3_LIBRARIES})
  endif (NOT GTK3_SUPPORT)
 else ()
  message (FATAL_ERROR "invalid/unknown GTK version, aborting")
 endif ()

# *NOTE*: unify include dirs and libraries; includers use GTK_INCLUDE_DIRS and GTK_LIBRARIES
 if (GTK3_USE)
  set (GTK_INCLUDE_DIRS ${GTK3_INCLUDE_DIRS})
  set (GTK_LIBRARIES ${GTK3_LIBRARIES})
 elseif (GTK2_USE)
  set (GTK_INCLUDE_DIRS ${GTK2_INCLUDE_DIRS})
  set (GTK_LIBRARIES ${GTK2_LIBRARIES})

  if (OPENGL_FOUND)
   set (GTKGLAREA_SUPPORT ON CACHE BOOL "enable GTK GL support" FORCE)
  endif (OPENGL_FOUND)
 endif ()

 message (STATUS "GTK_INCLUDE_DIRS: ${GTK_INCLUDE_DIRS}")
 message (STATUS "GTK_LIBRARIES: ${GTK_LIBRARIES}")

endif (GTK_SUPPORT AND GTK_USE)

