// -*- C++ -*-
//
// generated by wxGlade
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include "wx/xrc/xmlres.h"

#include "ace/Log_Msg.h"

#include "test_u_2.h"

// begin wxGlade: ::extracode
// end wxGlade



wxDialog_main::wxDialog_main(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
  wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
  // begin wxGlade: wxDialog_main::wxDialog_main
  button_1 = new wxButton(this, wxID_NEW, wxEmptyString);
  button_2 = new wxButton(this, wxID_COPY, wxEmptyString);
  button_3 = new wxButton(this, wxID_CLEAR, wxEmptyString);

  set_properties();
  do_layout();
  // end wxGlade
}

void wxDialog_main::set_properties()
{
  // begin wxGlade: wxDialog_main::set_properties
  SetTitle(wxT("dialog"));
  button_1->SetFocus();
  button_1->SetDefault();
  button_3->Enable(0);
  // end wxGlade
}


void wxDialog_main::do_layout()
{
  // begin wxGlade: wxDialog_main::do_layout
  wxBoxSizer* sizer_v_main = new wxBoxSizer(wxVERTICAL);
  sizer_v_main->Add(button_1, 0, 0, 0);
  sizer_v_main->Add(button_2, 0, 0, 0);
  sizer_v_main->Add(button_3, 0, 0, 0);
  SetSizer(sizer_v_main);
  sizer_v_main->Fit(this);
  Layout();
  // end wxGlade
}


BEGIN_EVENT_TABLE(wxDialog_main, wxDialog)
  // begin wxGlade: wxDialog_main::event_table
  EVT_BUTTON(wxID_ANY, wxDialog_main::button_1_clicked_cb)
  EVT_BUTTON(wxID_ANY, wxDialog_main::button_2_clicked_cb)
  EVT_BUTTON(wxID_ANY, wxDialog_main::button_3_clicked_cb)
  // end wxGlade
END_EVENT_TABLE();


void wxDialog_main::button_1_clicked_cb(wxCommandEvent &event)  // wxGlade: wxDialog_main.<event_handler>
{
  event.Skip();
  // notify the user that he hasn't implemented the event handler yet
  wxLogDebug(wxT("Event handler (wxDialog_main::button_1_clicked_cb) not implemented yet"));
}

void wxDialog_main::button_2_clicked_cb(wxCommandEvent &event)  // wxGlade: wxDialog_main.<event_handler>
{
  event.Skip();
  // notify the user that he hasn't implemented the event handler yet
  wxLogDebug(wxT("Event handler (wxDialog_main::button_2_clicked_cb) not implemented yet"));
}

void wxDialog_main::button_3_clicked_cb(wxCommandEvent &event)  // wxGlade: wxDialog_main.<event_handler>
{
  event.Skip();
  // notify the user that he hasn't implemented the event handler yet
  wxLogDebug(wxT("Event handler (wxDialog_main::button_3_clicked_cb) not implemented yet"));
}


// wxGlade: add wxDialog_main event handlers


class Test_U_wxWidgets_Application: public wxApp {
public:
  bool OnInit();
};

IMPLEMENT_APP(Test_U_wxWidgets_Application)

bool Test_U_wxWidgets_Application::OnInit()
{
  wxInitAllImageHandlers ();

  wxDialog_main* dialog_main = new wxDialog_main(NULL, wxID_ANY, wxEmptyString);

  if (!wxAppConsole::OnInit ())
  {
    ACE_DEBUG ((LM_ERROR,
                ACE_TEXT ("failed to wxAppConsole::OnInit(), aborting\n")));
    return false;
  } // end IF

  // step0: initialize XRC
  wxXmlResource* resource_p = wxXmlResource::Get ();
  if (unlikely (!resource_p))
  {
    ACE_DEBUG ((LM_ERROR,
                ACE_TEXT ("failed to wxXmlResource::Get(): \"%m\", aborting\n")));
    return false;
  } // end IF
  resource_p->InitAllHandlers ();

  // load widget tree
  wxObject* object_p = NULL;
  wxFileName file_name;
  file_name.Assign (ACE_TEXT_ALWAYS_CHAR ("test_u_2.xrc"),
                    wxPATH_NATIVE);
  if (unlikely (!resource_p->LoadFile (file_name)))
  {
    ACE_DEBUG ((LM_ERROR,
                ACE_TEXT ("failed to wxXmlResource::LoadFile(\"%s\"): \"%m\", aborting\n"),
                ACE_TEXT ("test_u_2.xrc")));
    return false;
  } // end IF

  if (unlikely (!resource_p->LoadDialog (dialog_main,
                                         NULL,
                                         ACE_TEXT_ALWAYS_CHAR ("dialog_main"))))
  {
    ACE_DEBUG ((LM_ERROR,
                ACE_TEXT ("failed to wxXmlResource::LoadDialog(\"%s\"): \"%m\", aborting\n"),
                ACE_TEXT ("dialog_main")));
    return false;
  } // end IF
#if defined (_DEBUG)
  ACE_DEBUG ((LM_DEBUG,
              ACE_TEXT ("loaded widget tree \"%s\"\n"),
              ACE_TEXT ("test_u_2.xrc")));
#endif // _DEBUG

  SetTopWindow (dialog_main);
  dialog_main->Show (true);

  return true;
}
