set (GSTREAMER_SUPPORT_DEFAULT ON)
if (UNIX)
 pkg_check_modules (PKG_GSTREAMER gstreamer-1.0)
 if (PKG_GSTREAMER_FOUND)
  set (GSTREAMER_FOUND TRUE)
  set (GSTREAMER_INCLUDE_DIRS "${PKG_GSTREAMER_INCLUDE_DIRS}")
  set (GSTREAMER_LIBRARIES "${PKG_GSTREAMER_LIBRARIES}")
 endif (PKG_GSTREAMER_FOUND)
elseif (WIN32)
 if (VCPKG_USE)
  find_package (GStreamer)
  if (GStreamer_FOUND)
   set (GSTREAMER_FOUND TRUE)
   set (GSTREAMER_INCLUDE_DIRS "${GStreamer_INCLUDE_DIR}")
   set (GSTREAMER_LIBRARIES "${GStreamer_LIBRARY}")
   set (GSTREAMER_LIB_DIR ${VCPKG_LIB_DIR}/bin)
  endif (GStreamer_FOUND)
 endif (VCPKG_USE)
 if (NOT GSTREAMER_FOUND)
#  file (TO_CMAKE_PATH "$ENV{LIB_ROOT}/gstreamer" GSTREAMER_ROOT_DIR)
#  set (GStreamer_ROOT_DIR "${GSTREAMER_ROOT_DIR}")
  set (CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH};$ENV{LIB_ROOT}/gstreamer/share/cmake")
  find_package (GStreamer)
  if (NOT GStreamer_FOUND)
   message (WARNING "could not find GStreamer, continuing")
  else ()
   message (STATUS "Found GStreamer ${GStreamer_VERSION}")
   set (GSTREAMER_FOUND TRUE)
   set (GSTREAMER_INCLUDE_DIRS "${GStreamer_INCLUDE_DIR};$ENV{LIB_ROOT}/gstreamer/include/glib-2.0")
   set (GSTREAMER_LIBRARIES "${GStreamer_LIBRARY};${pkgcfg_lib_PC_GStreamer_glib-2.0};${pkgcfg_lib_PC_GStreamer_gobject-2.0}")
   set (GSTREAMER_LIB_DIR "$ENV{LIB_ROOT}/gstreamer/bin")
  endif (NOT GStreamer_FOUND)
 endif (NOT GSTREAMER_FOUND)
endif ()
if (GSTREAMER_FOUND)
 option (GSTREAMER_SUPPORT "enable GStreamer support" ${GSTREAMER_SUPPORT_DEFAULT})
 if (GSTREAMER_SUPPORT)
  add_definitions (-DGSTREAMER_SUPPORT)
 endif (GSTREAMER_SUPPORT)
endif (GSTREAMER_FOUND)
