set (ONNXRT_SUPPORT_DEFAULT ON)
if (UNIX)
 if (EXISTS $ENV{ONNXRT_ROOT})
  set (ONNXRT_ROOT $ENV{ONNXRT_ROOT})
 else ()
  set (ONNXRT_ROOT $ENV{LIB_ROOT}/onnxruntime)
 endif (EXISTS $ENV{ONNXRT_ROOT})
 find_library (ONNXRT_LIBRARY libonnxruntime.so
               PATHS ${ONNXRT_ROOT}
               PATH_SUFFIXES lib
               DOC "searching for libonnxruntime.so"
               NO_DEFAULT_PATH)
 if (NOT ONNXRT_LIBRARY)
  message (WARNING "could not find libonnxruntime.so, continuing")
 else ()
  message (STATUS "Found libonnxruntime.so library \"${ONNXRT_LIBRARY}\"")
 endif (NOT ONNXRT_LIBRARY)
 if (ONNXRT_LIBRARY)
  set (ONNXRT_FOUND TRUE)
  set (ONNXRT_LIBRARIES ${ONNXRT_LIBRARY})
  set (ONNXRT_INCLUDE_DIRS ${ONNXRT_ROOT}/include)
 endif (ONNXRT_LIBRARY)
elseif (WIN32)
 if (VCPKG_USE)
  find_package (onnxruntime CONFIG)
  if (ONNXRUNTIME_FOUND)
   set (ONNXRT_FOUND TRUE)
   set (ONNXRT_INCLUDE_DIRS ${VCPKG_INCLUDE_DIR})
   set (ONNXRT_LIBRARIES ${VCPKG_LIB_DIR}/onnxruntime.lib)
   set (ONNXRT_LIB_DIR "${VCPKG_BIN_DIR}")
  endif (ONNXRUNTIME_FOUND)
 endif (VCPKG_USE)
 if (NOT ONNXRT_FOUND)
  if (EXISTS $ENV{ONNXRT_ROOT})
   set (ONNXRT_ROOT $ENV{ONNXRT_ROOT})
  else ()
   set (ONNXRT_ROOT $ENV{LIB_ROOT}/onnxruntime)
  endif (EXISTS $ENV{ONNXRT_ROOT})
  find_library (ONNXRT_LIBRARY onnxruntime.lib
                PATHS ${ONNXRT_ROOT}
                PATH_SUFFIXES lib
                DOC "searching for onnxruntime.lib"
                NO_DEFAULT_PATH)
  if (NOT ONNXRT_LIBRARY)
   message (WARNING "could not find onnxruntime.lib, continuing")
  else ()
   message (STATUS "Found onnxruntime.lib library \"${ONNXRT_LIBRARY}\"")
  endif (NOT ONNXRT_LIBRARY)
  if (ONNXRT_LIBRARY)
   set (ONNXRT_FOUND TRUE)
   set (ONNXRT_LIBRARIES "${ONNXRT_LIBRARY}")
   set (ONNXRT_INCLUDE_DIRS "${ONNXRT_ROOT}/include")
   set (ONNXRT_LIB_DIR "${ONNXRT_ROOT}/lib")
  endif (ONNXRT_LIBRARY)
 endif (NOT ONNXRT_FOUND)
endif ()
if (ONNXRT_FOUND)
 option (ONNXRT_SUPPORT "enable onnxruntime support" ${ONNXRT_SUPPORT_DEFAULT})
 if (ONNXRT_SUPPORT)
  add_definitions (-DONNXRT_SUPPORT)
 endif (ONNXRT_SUPPORT)
endif (ONNXRT_FOUND)
