set (TENSORFLOW_SUPPORT_DEFAULT ON)
if (UNIX)
# set (ENV{PKG_CONFIG_PATH} "/usr/local/lib/pkgconfig:$ENV{PKG_CONFIG_PATH}")
 pkg_check_modules (PKG_TENSORFLOW tensorflow)
 if (PKG_TENSORFLOW_FOUND)
  set (TENSORFLOW_FOUND TRUE)
  set (tensorflow_INCLUDE_DIRS "${PKG_TENSORFLOW_INCLUDE_DIRS}")
  set (tensorflow_LIBRARIES "${PKG_TENSORFLOW_LIBRARIES}")
 else ()
  find_library (TENSORFLOW_LIBRARY libtensorflow.so
                PATHS /usr/local
                PATH_SUFFIXES lib
                DOC "searching for libtensorflow.so"
                NO_DEFAULT_PATH)
  if (NOT TENSORFLOW_LIBRARY)
   message (WARNING "could not find libtensorflow.so, continuing")
  else ()
   message (STATUS "Found libtensorflow.so library \"${TENSORFLOW_LIBRARY}\"")
  endif (NOT TENSORFLOW_LIBRARY)
  if (TENSORFLOW_LIBRARY)
   set (TENSORFLOW_FOUND TRUE)
   set (tensorflow_LIBRARIES "${TENSORFLOW_LIBRARY}")
   set (tensorflow_INCLUDE_DIRS "/usr/local/include")
   set (tensorflow_LIB_DIR "/usr/local/lib")
  endif (TENSORFLOW_LIBRARY)

  find_library (TENSORFLOW_CC_LIBRARY libtensorflow_cc.so
                PATHS /usr/local
                PATH_SUFFIXES lib
                DOC "searching for libtensorflow_cc.so"
                NO_DEFAULT_PATH)
  if (NOT TENSORFLOW_CC_LIBRARY)
   message (WARNING "could not find libtensorflow_cc.so, continuing")
  else ()
   message (STATUS "Found libtensorflow_cc.so library \"${TENSORFLOW_CC_LIBRARY}\"")
  endif (NOT TENSORFLOW_CC_LIBRARY)
  find_library (TENSORFLOW_FRAMEWORK_LIBRARY libtensorflow_framework.so.2
                PATHS /usr/local
                PATH_SUFFIXES lib
                DOC "searching for libtensorflow_framework.so.2"
                NO_DEFAULT_PATH)
  if (NOT TENSORFLOW_FRAMEWORK_LIBRARY)
   message (WARNING "could not find libtensorflow_framework.so.2, continuing")
  else ()
   message (STATUS "Found libtensorflow_framework.so.2 library \"${TENSORFLOW_FRAMEWORK_LIBRARY}\"")
  endif (NOT TENSORFLOW_FRAMEWORK_LIBRARY)
  if (TENSORFLOW_CC_LIBRARY AND TENSORFLOW_FRAMEWORK_LIBRARY)
   set (TENSORFLOW_CC_FOUND TRUE)
   set (tensorflow_cc_LIBRARIES "${TENSORFLOW_CC_LIBRARY};${TENSORFLOW_FRAMEWORK_LIBRARY}")
   set (tensorflow_cc_INCLUDE_DIRS "/usr/local/include")
   set (tensorflow_cc_LIB_DIR "/usr/local/lib")
  endif (TENSORFLOW_CC_LIBRARY AND TENSORFLOW_FRAMEWORK_LIBRARY)
 endif (PKG_TENSORFLOW_FOUND)
elseif (WIN32)
 if (VCPKG_SUPPORT)
#  cmake_policy (SET CMP0074 OLD)
  find_package (tensorflow CONFIG)
  if (tensorflow_FOUND)
   set (TENSORFLOW_FOUND TRUE)
   if (CMAKE_BUILD_TYPE STREQUAL "Debug" OR
       CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    set (tensorflow_LIB_DIR "${VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}/debug/bin")
   else ()
    set (tensorflow_LIB_DIR "${VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}/bin")
   endif ()
  endif (tensorflow_FOUND)
 endif (VCPKG_SUPPORT)
 if (NOT TENSORFLOW_FOUND)
  if (EXISTS $ENV{TENSORFLOW_ROOT})
   set (TENSORFLOW_ROOT $ENV{TENSORFLOW_ROOT})
  else ()
   set (TENSORFLOW_ROOT $ENV{LIB_ROOT}/libtensorflow)
  endif (EXISTS $ENV{TENSORFLOW_ROOT})
  find_library (TENSORFLOW_LIBRARY tensorflow.lib
                PATHS ${TENSORFLOW_ROOT}
                PATH_SUFFIXES lib
                DOC "searching for tensorflow.lib"
                NO_DEFAULT_PATH)
  if (NOT TENSORFLOW_LIBRARY)
   message (WARNING "could not find tensorflow.lib, continuing")
  else ()
   message (STATUS "Found tensorflow.lib library \"${TENSORFLOW_LIBRARY}\"")
  endif (NOT TENSORFLOW_LIBRARY)
  if (TENSORFLOW_LIBRARY)
   set (TENSORFLOW_FOUND TRUE)
   set (tensorflow_LIBRARIES "${TENSORFLOW_LIBRARY}")
   set (tensorflow_INCLUDE_DIRS "${TENSORFLOW_ROOT}/include")
   set (tensorflow_LIB_DIR "${TENSORFLOW_ROOT}/lib")
  endif (TENSORFLOW_LIBRARY)
 endif (NOT TENSORFLOW_FOUND)
endif ()
if (TENSORFLOW_FOUND)
 option (TENSORFLOW_SUPPORT "enable tensorflow support" ${TENSORFLOW_SUPPORT_DEFAULT})
 if (TENSORFLOW_SUPPORT)
  add_definitions (-DTENSORFLOW_SUPPORT)
#  include_directories (${tensorflow_INCLUDE_DIRS})
 endif (TENSORFLOW_SUPPORT)
endif (TENSORFLOW_FOUND)
if (TENSORFLOW_CC_FOUND)
 option (TENSORFLOW_CC_SUPPORT "enable tensorflow C++ support" ${TENSORFLOW_SUPPORT_DEFAULT})
 if (TENSORFLOW_CC_SUPPORT)
  add_definitions (-DTENSORFLOW_CC_SUPPORT)
#  include_directories (${tensorflow_cc_INCLUDE_DIRS})
 endif (TENSORFLOW_CC_SUPPORT)
endif (TENSORFLOW_CC_FOUND)
