if (UNIX)
 set (CMAKE_THREAD_PREFER_PTHREAD ON)
 set (THREADS_PREFER_PTHREAD_FLAG ON)
# include (CheckLibraryExists)
# check_library_exists (pthread pthread_create "" HAVE_LIB_PTHREAD)
endif (UNIX)
find_package (Threads)
if (Threads_FOUND)
 if (NOT "${CMAKE_THREAD_LIBS_INIT}" STREQUAL "")
  message (STATUS "found thread support: \"${CMAKE_THREAD_LIBS_INIT}\"")
 else ()
  message (STATUS "found thread support: \"system\"")
 endif ()
endif (Threads_FOUND)
