if (UNIX)
 set (THREADS_PREFER_PTHREAD_FLAG ON)
endif (UNIX)
find_package (Threads)
if (Threads_FOUND)
 message (STATUS "found thread support: ${CMAKE_THREAD_LIBS_INIT}")
endif (Threads_FOUND)
