if (UNIX)
 set (THREADS_PREFER_PTHREAD_FLAG ON)
endif (UNIX)
find_package (Threads)
if (Threads_FOUND)
 if (NOT "${CMAKE_THREAD_LIBS_INIT}" STREQUAL "")
  message (STATUS "found thread support: \"${CMAKE_THREAD_LIBS_INIT}\"")
 else ()
  message (STATUS "found thread support: \"system\"")
 endif ()
endif (Threads_FOUND)
