set (VALGRIND_SUPPORT_DEFAULT ON)
if (UNIX)
 include (CheckIncludeFiles)
 check_include_files (valgrind/valgrind.h HAVE_VALGRIND_H)
#  include (CheckLibraryExists)
#  check_library_exists (libvalgrind "" "" HAVE_LIB_VALGRIND)
 pkg_check_modules (VALGRIND valgrind)
endif (UNIX)
if (VALGRIND_FOUND)
 option (VALGRIND_SUPPORT "enable valgrind support" ${VALGRIND_SUPPORT_DEFAULT})
 if (VALGRIND_SUPPORT)
  option (VALGRIND_USE "enable valgrind" OFF)
  if (VALGRIND_USE)
   add_definitions (-DVALGRIND_USE)
  endif (VALGRIND_USE)
 endif (VALGRIND_SUPPORT)
endif (VALGRIND_FOUND)
