name: 'install_ACE_win32'
description: 'install ACE on the runner'
inputs:
 os:  # id of input
  description: 'runner OS'
  required: true
runs:
 using: "composite"
 steps:
  - uses: lukka/run-vcpkg@v7.4
    with:
     setupOnly: true
     vcpkgGitCommitId: '4428702c1c56fdb7cb779584efdcba254d7b57ca'
  - run: vcpkg install ace[xml]
    shell: cmd
#    if: inputs.os == 'ubuntu-latest'
#  - run:
#    shell: bash
#    if: inputs.os == 'windows-latest'
#  - run:
#   shell: bash
#   if: inputs.os == 'macos-latest'
