name: 'install_ACE_win32'
description: 'install ACE on the runner'
inputs:
 os:  # id of input
  description: 'runner OS'
  required: true
runs:
 using: "composite"
 steps:
  - uses: lukka/run-vcpkg@v10
    with:
     vcpkgDirectory: '${{ github.workspace }}/vcpkg'
     vcpkgGitCommitId: '30a20e8f15ff26eec665205dea52f4ffc6f0814b'
     # Run vcpkg with the command specified by the `runVcpkgFormatString` input.
     runVcpkgInstall: true
     #vcpkgJsonGlob: '**/vcpkg.json'
     vcpkgJsonGlob: '${{ runner.workspace }}/b/Common/vcpkg.json'
     appendedCacheKey: vcpkginstall
