if (UNIX)
# include (FindPkgConfig)
# pkg_check_modules (PKG_LIBPNG libpng)
 find_library (PNG_LIBRARY libpng16.so.16
               DOC "searching for libpng")
 if (NOT PNG_LIBRARY)
  message (WARNING "could not find libpng, continuing")
 else ()
  message (STATUS "Found libpng \"${PNG_LIBRARY}\"")
  set (PNG_FOUND TRUE)
  set (PNG_LIBRARIES "${PNG_LIBRARY}")
 endif (NOT PNG_LIBRARY)
elseif (WIN32)
 if (VCPKG_SUPPORT AND NOT DEFINED ENV{LIB_ROOT})
#  cmake_policy (SET CMP0074 OLD)
  find_package (libpng)
  if (libpng_FOUND)
   message (STATUS "found libpng")
   set (PNG_FOUND TRUE)
   set (PNG_INCLUDE_DIRS ${VCPKG_INCLUDE_DIR_BASE})
   set (PNG_LIB_DIR "${VCPKG_LIB_DIR}/bin")
  endif (libpng_FOUND)
 endif (VCPKG_SUPPORT AND NOT DEFINED ENV{LIB_ROOT})
 if (NOT PNG_FOUND)
  message (STATUS "found libpng")
  set (PNG_FOUND TRUE)
  set (PNG_INCLUDE_DIRS $ENV{LIB_ROOT}/libpng/build;$ENV{LIB_ROOT}/libpng)
  set (PNG_LIBRARIES $ENV{LIB_ROOT}/libpng/build/$<CONFIG>/libpng16${LIB_FILE_SUFFIX}.lib)
  set (PNG_LIB_DIR $ENV{LIB_ROOT}/zlib/build/$<CONFIG>;$ENV{LIB_ROOT}/libpng/build/$<CONFIG>)
 endif (NOT PNG_FOUND)
endif ()
if (PNG_FOUND)
 option (LIBPNG_SUPPORT "enable libpng support" ON)
 if (LIBPNG_SUPPORT)
  add_definitions (-DLIBPNG_SUPPORT)
 endif (LIBPNG_SUPPORT)
endif (PNG_FOUND)
