if (UNIX)
 find_path (STB_IMAGE_HEADER stb_image.h
            PATHS $ENV{LIB_ROOT}
            PATH_SUFFIXES stb
            DOC "searching for stb_image")
 if (NOT STB_IMAGE_HEADER)
  message (WARNING "could not find stb_image.h, continuing")
 else ()
  message (STATUS "Found stb_image.h \"${STB_IMAGE_HEADER}\"")
  set (STB_IMAGE_FOUND TRUE)
  set (STB_IMAGE_INCLUDE_DIRS "${STB_IMAGE_HEADER}")
 endif (NOT STB_IMAGE_HEADER)
elseif (WIN32)
 if (VCPKG_USE)
#  cmake_policy (SET CMP0074 OLD)
  find_package (Stb)
  if (STB_FOUND)
   message (STATUS "found stb")
   set (STB_IMAGE_FOUND TRUE)
   set (STB_IMAGE_INCLUDE_DIRS "${Stb_INCLUDE_DIR}")
  endif (STB_FOUND)
 endif (VCPKG_USE)
 if (NOT STB_IMAGE_FOUND)
  find_path (STB_IMAGE_HEADER stb_image.h
             PATHS $ENV{LIB_ROOT}
             PATH_SUFFIXES stb
             DOC "searching for stb_image")
  if (NOT STB_IMAGE_HEADER)
   message (WARNING "could not find stb_image.h, continuing")
  else ()
   message (STATUS "Found stb_image.h \"${STB_IMAGE_HEADER}\"")
   set (STB_IMAGE_FOUND TRUE)
   set (STB_IMAGE_INCLUDE_DIRS "${STB_IMAGE_HEADER}")
  endif (NOT STB_IMAGE_HEADER)
 endif (NOT STB_IMAGE_FOUND)
endif ()
if (STB_IMAGE_FOUND)
 option (STB_IMAGE_SUPPORT "enable stb_image support" ON)
 if (STB_IMAGE_SUPPORT)
  add_definitions (-DSTB_IMAGE_SUPPORT)
 endif (STB_IMAGE_SUPPORT)
endif (STB_IMAGE_FOUND)
